#!/bin/bash

set -eu

#environment=$1
#re="^(staging|production)$"
#if [[ ! $environment =~ $re ]]
#then
#    echo "usage: ./terraform [staging|production] command"
#    exit 1
#fi
#
#shift
#
#export TF_DATA_DIR=.terraform_${environment}
export TF_DATA_DIR=.terraform

# init if needed
if [ ! -d "${TF_DATA_DIR}" ]; then
    terraform init
fi

if [ $# -eq 0 ]; then
    set -- plan .
fi

#export TF_VAR_environment="$environment"
export TF_CLI_ARGS="-var-file=shared.tfvars"

terraform "$@"

# set the stage for ansible
# terraform state pull | ./scripts/state_to_ansible_inventory.py > "../ansible/hosts.${}"
