# ClusterConfig with a normal nodegroup and a Fargate profile.
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: qareports-eks-cluster
  region: us-east-1
  version: "1.16"
  # I need to make it use a custom security group so that it'll be added to RDS allowed security groups
vpc:
  id: "vpc-085116ed2a0c4bf5f"
  cidr: "192.168.0.0/16"
  nat:
    gateway: Disable
  subnets:
    private:
      us-east-1d:
          id: "subnet-0eed193802ba7b584"
          cidr: "192.168.96.0/19"
      us-east-1c:
          id: "subnet-08fda885d66690558"
          cidr: "192.168.64.0/19"
    public:
      us-east-1d:
          id: "subnet-0397ab094ac38b559"
          cidr: "192.168.32.0/19"
      us-east-1c:
          id: "subnet-0ee9da5a5096de940"
          cidr: "192.168.0.0/19"

nodeGroups:
  - name: ng-1
    instanceType: t3a.small
    desiredCapacity: 1

fargateProfiles:
  - name: fp-staging
    selectors:
      - namespace: qareports-staging
  - name: fp-production
    selectors:
      - namespace: qareports-production
