# ClusterConfig with a normal nodegroup and a Fargate profile.
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: qareports-eks-cluster
  region: us-east-1
  version: "1.16"
  # I need to make it use a custom security group so that it'll be added to RDS allowed security groups
vpc:
  id: "vpc-0ca76d0fd7625cc5b"
  cidr: "192.168.0.0/16"
  nat:
    gateway: Disable
  subnets:
    private:
      us-east-1d:
          id: "subnet-0dee79e9e8eb42409"
          cidr: "192.168.96.0/19"
      us-east-1c:
          id: "subnet-07ace1ad935ac1a55"
          cidr: "192.168.64.0/19"
    public:
      us-east-1d:
          id: "subnet-05281256c75790d05"
          cidr: "192.168.32.0/19"
      us-east-1c:
          id: "subnet-0c8d73f7c56cd3f1a"
          cidr: "192.168.0.0/19"

nodeGroups:
  - name: ng-1
    instanceType: t3a.small
    desiredCapacity: 1

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: kubernetes-dashboard
  - name: fp-staging
    selectors:
      - namespace: qareports-staging
  - name: fp-production
    selectors:
      - namespace: qareports-production
