# ClusterConfig with a normal nodegroup and a Fargate profile.
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: qareports-eks-cluster
  region: us-east-1
  version: "1.16"
  # I need to make it use a custom security group so that it'll be added to RDS allowed security groups
vpc:
  id: "vpc-002a3b819b8de6be5"
  cidr: "192.168.0.0/16"
  nat:
    gateway: Disable
  subnets:
    private:
      us-east-1d:
          id: "subnet-0a09da92f67b7d890"
          cidr: "192.168.96.0/19"
      us-east-1c:
          id: "subnet-00590379ca8660417"
          cidr: "192.168.64.0/19"
    public:
      us-east-1d:
          id: "subnet-0e0d942fa29c6cd2b"
          cidr: "192.168.32.0/19"
      us-east-1c:
          id: "subnet-0bdf3cfc5344cd4ce"
          cidr: "192.168.0.0/19"

nodeGroups:
  - name: ng-1
    instanceType: t3a.small
    desiredCapacity: 1

fargateProfiles:
  - name: fp-staging
    selectors:
      - namespace: qareports-staging
  - name: fp-production
    selectors:
      - namespace: qareports-production
