#
# Deploy one squad container running qareports-listener
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qareports-listener-deployment
  labels:
    app: qareports-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qareports-listener
  template:
    metadata:
      labels:
        app: qareports-listener
    spec:
      containers:
      - name: qareports-listener
        image: squadproject/squad:0.7
        command: ["sh", "-c"]
        args:
        - squad-listener
        env:
        - name: DATABASE
          value: "ENGINE=django.db.backends.postgresql_psycopg2:NAME=chawsqareports:HOST=terraform-20200527105912595800000001.ch4dokfnfsnh.us-east-1.rds.amazonaws.com:USER=qareports:PASSWORD=easy_password"
        - name: SQUAD_CELERY_BROKER_URL
          value: "amqp://192.168.53.153"
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"
