apiVersion: v1
kind: Secret
metadata:
    name: qareports-environment
type: Opaque
data:
    # Secrets can only contain base64 encoded values, bummer!
    # ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:HOST=172.16.0.10:USER=squad:PASSWORD=squad
    DATABASE: RU5HSU5FPWRqYW5nby5kYi5iYWNrZW5kcy5wb3N0Z3Jlc3FsX3BzeWNvcGcyOk5BTUU9c3F1YWQ6SE9TVD0xNzIuMTYuMC4xMDpVU0VSPXNxdWFkOlBBU1NXT1JEPXNxdWFk

    # amqp://172.16.0.10
    SQUAD_CELERY_BROKER_URL: YW1xcDovLzE3Mi4xNi4wLjEw

#XDG_DATA_HOME={{install_base}}/data
#PGDATABASE={{database_name}}
#PGHOST={{database_hostname}}
#PGUSER={{database_user}}
#{% if linaro_ldap %}
#SQUAD_EXTRA_SETTINGS={{install_base}}/linaro_ldap.py
#{% endif %}
#SQUAD_SITE_NAME="{{site_name}}"
#SQUAD_LOG_LEVEL=INFO
#SQUAD_EMAIL_FROM=qa-reports@linaro.org
#SQUAD_ADMINS='Antonio Terceiro <antonio.terceiro@linaro.org>, Milosz Wasilewski <milosz.wasilewski@linaro.org>, Charles Oliveira <charles.oliveira@linaro.org>'
#ENV=production
#GUNICORN_CMD_ARGS="--workers 2"
#SQUAD_BASE_URL=https://{{server_name}}
#SQUAD_HOSTNAME={{inventory_hostname}}
#{% if sentry_dsn is defined %}
#SENTRY_DSN={{sentry_dsn}}
#{% endif %}
