#
# Autoscale pods to have minumum of 2 pods up to 10 pods
# depending on CPU average load
#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: qareports-fetch-worker-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qareports-fetch-worker-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---

#
# Deploy one pod of squad container to run as worker
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qareports-fetch-worker-deployment
  labels:
    app: qareports-fetch-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qareports-fetch-worker
  template:
    metadata:
      labels:
        app: qareports-fetch-worker
    spec:
      containers:
      - name: qareports-fetch-worker
        image: squadproject/squad:0.7
        command: ["sh", "-c"]
        args:
        - squad-worker --exclude-queues=core_notification,ci_quick
        env:
        - name: DATABASE
          value: "ENGINE=django.db.backends.postgresql_psycopg2:NAME=chawsqareports:HOST=terraform-20200526103502409100000001.ch4dokfnfsnh.us-east-1.rds.amazonaws.com:USER=qareports:PASSWORD=easy_password"
        - name: SQUAD_CELERY_BROKER_URL
          value: "amqp://192.168.37.22"
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"
