#
# Apply migration before each update
apiVersion: batch/v1
kind: Job
metadata:
  name: qareports-migration
spec:
  template:
    metadata:
      name: qareports-migration
    spec:
      restartPolicy: Never
      containers:
      - name: qareports-migration
        image: squadproject/squad
        command: ["squad-admin"]
        args:
        - migrate
        envFrom:
        - secretRef:
            name: qareports-environment
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"
