#
# Autoscale pods to have minumum of 2 pods up to 10 pods
# depending on CPU average load
#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: qareports-web-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qareports-web-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---

#
# Expose qareports-web pods externally
#
apiVersion: v1
kind: Service
metadata:
  name: qareports-web-service
spec:
  selector:
    app: qareports-web
  ports:
    - port: 80
  type: LoadBalancer
  externalIPs:
  - 192.168.50.10  # it'll take another dns address when in production

---

#
# Deploy initially one pod of qareports-web container
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qareports-web-deployment
  labels:
    app: qareports-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qareports-web
  template:
    metadata:
      labels:
        app: qareports-web
    spec:
      # TODO: do not run as root
      securityContext:
        runAsUser: 0
      containers:
      - name: qareports-web
        image: qareports/squad:0.6
        command: ["sh", "-c"]
        args:
        - service apache2 start && squad --timeout=60 --workers=2 --fast --log-level DEBUG
        ports:
        - containerPort: 80
        env:
        - name: DATABASE
          value: "ENGINE=django.db.backends.postgresql_psycopg2:NAME=chawsqareports:HOST=terraform-20200526103502409100000001.ch4dokfnfsnh.us-east-1.rds.amazonaws.com:USER=qareports:PASSWORD=easy_password"
        - name: SQUAD_CELERY_BROKER_URL
          value: "amqp://192.168.37.22"
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"
