#
# Deploy one squad container running squad-listener
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad-listener-deployment
  labels:
    app: squad-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squad-listener
  template:
    metadata:
      labels:
        app: squad-listener
    spec:
      containers:
      - name: squad-listener
        image: squadproject/squad:0.7
        command: ["sh", "-c"]
        args:
        - squad-listener
        env:
        - name: DATABASE
          value: "ENGINE=django.db.backends.postgresql_psycopg2:NAME=chawsqareports:HOST=terraform-20200525114035650700000001.ch4dokfnfsnh.us-east-1.rds.amazonaws.com:USER=qareports:PASSWORD=easy_password"
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"
