#
# Deploy one squad container for squad-scheduler
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad-scheduler-deployment
  labels:
    app: squad-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squad-scheduler
  template:
    metadata:
      labels:
        app: squad-scheduler
    spec:
      containers:
      - name: squad-scheduler
        image: squadproject/squad:0.7
        command: ["sh", "-c"]
        args:
        - squad-scheduler --schedule=/app/celerybeat-schedule.db
        ports:
        - containerPort: 80
        env:
        - name: DATABASE
          value: "ENGINE=django.db.backends.postgresql_psycopg2:NAME=chawsqareports:HOST=terraform-20200526103502409100000001.ch4dokfnfsnh.us-east-1.rds.amazonaws.com:USER=qareports:PASSWORD=easy_password"
        - name: SQUAD_CELERY_BROKER_URL
          value: "amqp://192.168.37.22"
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"
