#
# Deploy one squad container for squad-scheduler
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad-scheduler-deployment
  labels:
    app: squad-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squad-scheduler
  template:
    metadata:
      labels:
        app: squad-scheduler
    spec:
      containers:
      - name: squad-scheduler
        image: squadproject/squad
        command: ["sh", "-c"]
        args:
        - squad-scheduler --schedule=/app/celerybeat-schedule.db
        envFrom:
        - secretRef:
            name: squad-environment
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"
