#
# Autoscale pods to have minumum of 2 pods up to 10 pods
# depending on CPU average load
#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: squad-fetch-worker-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: squad-fetch-worker-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---

#
# Deploy one pod of squad container to run as worker
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad-fetch-worker-deployment
  labels:
    app: squad-fetch-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squad-fetch-worker
  template:
    metadata:
      labels:
        app: squad-fetch-worker
    spec:
      containers:
      - name: squad-fetch-worker
        image: squadproject/squad
        command: ["sh", "-c"]
        args:
        - squad-worker --exclude-queues=ci_poll,ci_quick,core_notification,core_postprocess,core_quick,core_reporting --concurrency=1 --without-mingle
        envFrom:
        - secretRef:
            name: squad-environment
        resources:
          requests:
            memory: "512M"
            cpu: "500m"
          limits:
            memory: "1025M"
            cpu: "1000m"
        volumeMounts:
        - name: squad-secret-key
          mountPath: /app/secret.dat
          subPath: secret.dat

      volumes:
      - name: squad-secret-key
        configMap:
          name: squad-secret-key
