#
# Autoscale pods to have minumum of 2 pods up to 10 pods
# depending on CPU average load
#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: squad-worker-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: squad-worker-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---

#
# Deploy initially one pod of squad container as worker
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad-worker-deployment
  labels:
    app: squad-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squad-worker
  template:
    metadata:
      labels:
        app: squad-worker
    spec:
      containers:
      - name: squad-worker
        image: squadproject/squad
        command: ["sh", "-c"]
        args:
        - squad-worker --exclude-queues=ci_fetch --concurrency=3 --without-mingle
        envFrom:
        - secretRef:
            name: squad-environment
        env:
        - name: SQUAD_EMAIL_PORT
          value: "1025"
        - name: SQUAD_EMAIL_HOST
          value: "aws-smtp-relay.kube-system"  # aws-smtp-relay => service name, kube-system => namespace
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"
