#
# Autoscale pods to have minumum of 2 pods up to 10 pods
# depending on CPU average load
#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: squad-web-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: squad-web-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---

#
# Expose squad-web pods externally
#
apiVersion: v1
kind: Service
metadata:
  name: squad-web-service
spec:
  selector:
    app: squad-web
  ports:
    - port: 80
  type: LoadBalancer
  externalIPs:
  - 172.31.4.240  # it'll take another dns address when in production

---

#
# Apache configuration
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: squad-web-apache-conf
data:
  squad.conf: |-
    # Load some mods
    LoadModule cgid_module modules/mod_cgid.so
    LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
    LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
    LoadModule vhost_alias_module modules/mod_vhost_alias.so

    # Virtual host setup
    <VirtualHost *:80>
      ProxyPreserveHost On

      # Security headers
      Header always set Strict-Transport-Security "max-age=31536000; includeSubdomains;"
      Header always set X-Content-Type-Options "nosniff;"
      Header always set Content-Security-Policy "default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' www.gravatar.com; style-src 'self' 'unsafe-inline'; font-src 'self';"

      # Set default cache controll if there isn't any
      Header setIfEmpty Cache-Control "no-cache"

      # Serve static files separately
      Alias /static "/squad_static/static"
      <Directory "/squad_static/static">
        Require all granted
      </Directory>

      # Pass routing to gunicorn
      ProxyPassMatch ^/static !
      ProxyPass "/" http://127.0.0.1:8000/
    </VirtualHost>

---

#
# Deploy initially one pod of squad-web container
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad-web-deployment
  labels:
    app: squad-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squad-web
  template:
    metadata:
      labels:
        app: squad-web
    spec:
      initContainers:
      - name: init-squad-web
        image: squadproject/squad
        command: ["cp", "-r", "/app/static", "/squad_static"]
        volumeMounts:
        - name: static-files
          mountPath: /squad_static
      containers:
      - name: apache2
        image: httpd:2.4
        command: ["sh", "-c"]
        args:
        - cat squad.conf >> conf/httpd.conf && httpd -D FOREGROUND
        ports:
        - containerPort: 80
        volumeMounts:
        - name: squad-web-apache-conf
          mountPath: /usr/local/apache2/squad.conf
          subPath: squad.conf
        - name: static-files
          mountPath: /squad_static
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"

      - name: squad-web
        image: squadproject/squad
        command: ["sh", "-c"]
        args:
        - squad --timeout=60 --workers=2 --fast --log-level DEBUG
        envFrom:
        - secretRef:
            name: squad-environment

        # Inject ldap into container
        env:
        - name: SQUAD_EXTRA_SETTINGS
          value: "/app/linaro_ldap.py"
        volumeMounts:
        - name: squad-ldap-conf
          mountPath: /app/linaro_ldap.py
          subPath: linaro_ldap.py
        - name: squad-ldap-conf
          mountPath: /usr/local/lib/python3.7/dist-packages/linaro_ldap_backends.py
          subPath: linaro_ldap_backends.py

        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"

      volumes:
      - name: squad-web-apache-conf
        configMap:
          name: squad-web-apache-conf

      - name: static-files
        emptyDir: {}

      - name: squad-ldap-conf
        configMap:
          name: squad-ldap-conf
