#
# Deploy one squad container running squad-listener
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad-listener-deployment
  labels:
    app: squad-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squad-listener
  template:
    metadata:
      labels:
        app: squad-listener
    spec:
      containers:
      - name: squad-listener
        image: squadproject/squad
        command: ["sh", "-c"]
        args:
        - squad-listener
        envFrom:
        - secretRef:
            name: squad-environment
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"
