apiVersion: v1
kind: Service
metadata:
  name: squad-web-service
spec:
  selector:
    app: squad-web
  ports:
    - port: 80
  type: LoadBalancer
  #externalTrafficPolicy: Local
  externalIPs:
  - 192.168.50.10
