apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad-web-deployment
  labels:
    app: squad-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: squad-web
  template:
    metadata:
      labels:
        app: squad-web
    spec:
      containers:
      - name: squad-web
        image: qareports/squad:0.6
        command: ["sh", "-c"]
        args:
        - service apache2 start && squad --timeout=60 --workers=2 --fast --log-level DEBUG
        ports:
        - containerPort: 80
        env:
        - name: DATABASE
          value: "ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:HOST=172.16.0.10:USER=squad:PASSWORD=squad"
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "512M"
            cpu: "500m"
