apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: squad-web-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: squad-web-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
